### ISSUE TITLE
Make Optional File::create("test_item) - Crashes release mode desktop app 

### ISSUE THREAD

**Issue by enzotar** [Bundlr-Network/rust-sdk#5]
Can we make this test file creation optional in send_transaction(). It crashes desktop apps on release mode due to read only privileges.

https://github.com/Bundlr-Network/rust-sdk/blob/9740eff13780b780c83846c55848c8c023756b19/src/bundlr.rs#L43-L44

**Comment by samuelvanderwaal** [comment]
Fixed in #6
